# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Path to Python project root (adjust if dependencies are in a subfolder)
    schedule:
      interval: "daily"
    open-pull-requests: true
    rebase-strategy: auto
    commit-message:
      prefix: "chore(deps):"
      include-details: true
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major"] # Skip major versions for Python
